<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="1" failures="1" disabled="0" errors="0" time="0.001" timestamp="2022-08-07T23:14:48.372" name="AllTests">
  <testsuite name="HashTableTest" tests="1" failures="1" disabled="0" skipped="0" errors="0" time="0" timestamp="2022-08-07T23:14:48.372">
    <testcase name="SampleTest" file="/opt/project/cmu15-445/bustub-private/test/container/hash_table_test.cpp" line="27" status="run" result="completed" time="0" timestamp="2022-08-07T23:14:48.372" classname="HashTableTest">
      <failure message="unknown file&#x0A;C++ exception with description &quot;can&apos;t open db file&quot; thrown in the test body." type=""><![CDATA[unknown file
C++ exception with description "can't open db file" thrown in the test body.]]></failure>
    </testcase>
  </testsuite>
</testsuites>
